apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUtES2U0YWVwTnVlQUIrOENxQ3M1Mnd3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05HSXpNbU0xTmpjdE16SmxaUzAwWTJKaUxUaGxZakF0WkRObE5qVXhNbVk1Wm1ZMApNQ0FYRFRJME1Ea3lPREUwTkRZMU9Wb1lEekl3TlRRd09USXhNVFUwTmpVNVdqQXZNUzB3S3dZRFZRUURFeVEwCllqTXlZelUyTnkwek1tVmxMVFJqWW1JdE9HVmlNQzFrTTJVMk5URXlaamxtWmpRd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FEaFFJM2JOSFVSTlN2U3A3b1o5K21FalR6cEZmbUFKWEErMDZnNwo1QVFEZm52bENzZk1yVlB0SHNCdVY0Q3dILzJncG1JbTRaOGVCdFJKUWIxQ3ZUc0R4QmZtUnFnRWFHNkYrK0poCjkxKy9SL2w2TkRMR0ZDeVk0dFRRc3R4d0d6RmlzditHWXgySDdBWm02Y3FKOXdZcmJ0M0tpZnNacjlIbEoxWjIKanIrWGxWNHlGR1BFMTVvcXNDQ0V0bGozTUMyWFdJUkNzcW4xcHhPRERyZXhHZkNsS25VSlh0K0hxdUZqVUNlbQozcURhMlFoeTFxbjZhcG5qZFdQMW15TENHM3VHS2luNmprbTlFWGtpM1FiRTEvSWM5bkVZQ1k4a25zajJtVTQrCjhaTEhPck1Tck5ZdVJXaXU4Zjl5ZStQc1dvR0pwN1RRK0E0dHFpdkhzMlkvTWt5RjBTSVlIODlBUjcyNTN1OE4Kem5wMEtYaUQzYlhSTHc0WnlHbzZ2WUN4TmpsU1Y2akZqOGgxZUMyRGhEVjQ1NnpqWks1bTE3dE8wanlqcXQ0bQpqKzdNalFuQlJOdm9IQXE0ZkVETWRPMTJBV2NVaEZZcFhLeTZuUFVVa1pUalZmbU9ydjNuekx0bVJhd2gyVGZWCkVheFd1NHNRRmxCUFVQNytpN0pMRGRyYmN4TUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSG14Ny9za0NaQVNUNFV2WTdTQ05mdjRDSlQ4TUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQWRGbmcrZk95Q24raFJTMnM1T3FqR3RTUFJaRi80M0RJang3TW8rNVFICjdOaTZqbVRNRnVaOTJmb1Q0M01jZENUdXhmcDd6a3A3R0NhdENaYXZ1ZHhkUUVXUitqbEFBTHV0V05scTlpSTgKU3oxQTZEZkFPcTJndEhmMXRNbVo1RXV2Yld3UUx6Ujl0RFliRk1GbGlMdzh5VzBGT0d3N3dXTFY1YlFTNmpzUApsL1VrTnI3TFYvTmRSTFNUdHFDVk9icllNNjNHeFJnZ2daUHB6aFNwOWNQS0RpS1FyazM0TTlFRk8veE5FbWphCk5aeCtrcytNSU1RZSt4OXJwQUlhOCtoUWs3UkRsVFhxK3JvdERCdStyY2dzd1hhbDJ1bi9ncmlTRm15U0VUYTQKbUI0YmZPRkdRZFcvODNvcUhlbkVPbzQ1dHR0UjBjNmNUVVd3YmlrbnZZODJWVEhaYnRxQjhMU1FMMGw2OUdoTwpWRXJZcjJUMGdwdU1UZ2ZyNXoycUcveCtWRmhzK01abFpIR1BCcmUvd1BsT3I3dXdWbS9nR1J0LzFrMkZVL3ZKClBaMlZQNDFNaXZPN1ZUZHpXTGplRFhNakR0SEsvNWtXRkdBaGZ2M0JvRmNYWm5BRkxDQXlwTm1tS2lRc2tKSmMKOEw3UW9LOHl3WkxEU0IyQ01hOUxHdWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.239.91.206
  name: gke_devops-project-437014_us-central1-c_devopstest
contexts:
- context:
    cluster: gke_devops-project-437014_us-central1-c_devopstest
    user: gke_devops-project-437014_us-central1-c_devopstest
  name: gke_devops-project-437014_us-central1-c_devopstest
current-context: gke_devops-project-437014_us-central1-c_devopstest
kind: Config
preferences: {}
users:
- name: gke_devops-project-437014_us-central1-c_devopstest
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
