apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: jenkins 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: your-dockerhub-username/frontend-app:latest 
        ports:
        - containerPort: 3000 

