apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  namespace: jenkins
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 3000  # Redirige el puerto 80 del LoadBalancer al puerto 3000 de tu aplicación
  selector:
    app: frontend-app
